### PR TITLE
pangaea module addition, fixed xarray inplace error

### PR DESCRIPTION
**Pull request by saralytle**

### CODE REVIEW

**Comment by snowman2** [comment]
@mgeheran @cekees I can transfer ownership of pangaea & gazar to `erdc` if you temporarily grant me create repository permissions.

**Review by mgeheran — APPROVED** [review]

**Review by aat669 — COMMENTED** [review]
these commands need to be reordered:
#   $ conda env create -f  rapidpy_env.yml
activate the rapidpy_env environment
run the following command
# python setup.py develop

**Comment by saralytle** [comment]
> these commands need to be reordered:
> $ conda env create -f  rapidpy_env.yml
> activate the rapidpy_env environment
> run the following command
> python setup.py develop

Fixed!

**Comment by saralytle** [comment]
Oops! accidentally closed the request instead of the comment

**Review by aat669 — APPROVED** [review]

**Review by aat669 — APPROVED** [review]

**Pull request merged**
