### PR TITLE
mpg/inflow

### PR DESCRIPTION
**Pull request by mgeheran**
This is integrates recent changes on master with mjshaw's inflow updates.

### CODE REVIEW

**Comment by mgeheran** [comment]
@mjshaw1 I made a few modifications that mostly deal with naming conventions. Please let me know if there is any functionality that I left out. The reservoir routing parameters for RAPID are up next.

**Review by mjshaw1 — APPROVED** [review]

**Review by mjshaw1 — APPROVED** [review]
I think this could work for some cases.  There are instances when the ERA5 or ERA Interim data are made by NCO functions whence the order of dimensions are shuffled or their names use caps, for example.  I had made a generic CreateInflowFileFromERARunoff.py class that sort of handled every likely permutation of ERA5 or ERA Interim dimensions and capitalizations that could be used in lsm_rapid_process for either 5 or Interim.  So that could be an alternative way about it.  On the other hand, I think if we lean RAPIDpy more towards a formal generic incoming runoff netCDF format regardless of what LSM is the source and enforce that (kind of like what WRF's pre-processor and LIS's pre-processor tend towards), this becomes a moot point.

**Review by mjshaw1 — COMMENTED** [review]
This looks good.  Would you like an independent test run of the functionality here?  And for all cases?  (Assuming that has already been done.)

Another couple quick notes:

- joules is actually JULES (something I've noticed ed in the past in RAPIDpy)
- As mentioned in another note wrt this pull request but another change, an other way about some of this (ERA5 and Interim) could be to handle both ERA5 and ERA Interim in one CreateInflowFileFromERARunoff that deals with various permutations of dimensions including caps or lower case naming of the RO/ro variable
- I might consider requiring users to put runoff netCDF into a single standard format including wrt time increments etc to avoid ever-growing cases to handle more and more instances (conversion of 1 hour to three, various grids, etc etc); that could take the maintenance and development load off the group wrt this to then free up more capacity to develop other more generic functional and scientific capacity, python and other updates/releases, "support" otherwise, etc...and does make maintenance easier and more straight forward otherwise.  But I can see some advantages of also handling various instances within code somehow - so, it's just sort of a decision node that might be worth considering, is all.

**Comment by mgeheran** [comment]
Hello, @mjshaw1. Thank you for reviewing. We each took a different approach to handling the ECMWF netCDF variable names, but the functionality should be equivalent. As far as testing goes, I have tested the cases for which we currently have data on the repository. If you are aware of any new cases that are not properly handled, we need to address that.

**Comment by mgeheran** [comment]
@mjshaw1 with respect to the other issues you mentioned:
- JULES is consistently misspelled throughout the repository. I think this is low priority.
- I resisted combining ERA Interim and ERA5 functionality into the same subclass to keep them logically separated. I believe this potentially simplifies the debugging process. 
- A standard runoff input format would certainly make our workflow more efficient. I agree that we should consider this option.

**Review by saralytle — APPROVED** [review]
Passed all tests under 2.7, failed 10 tests under test_gis.py with 3.8 for weight table generation

**Review by aat669 — APPROVED** [review]

**Pull request merged**
